//
//  PaintCodeTutorial.h
//  ProjectName
//
//  Created by jmt on 16/9/22.
//  Copyright (c) 2016 guaji. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PaintCodeTutorial : NSObject

// Drawing Methods
+ (void)drawStopWatch;
+ (void)drawStopWatchHand;

@end
